<a href="https://colab.research.google.com/github/Ciastkk45/kursAI-sb10/blob/main/2_biblioteka_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version


Python 3.11.11


In [3]:
!pip freeze | grep numpy

numpy==1.26.4


In [8]:
# ważne - importowanie numpy
import numpy as np

#tworzenie tablicy
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Array2x6 - ksztalt: {np.shape(array2x6)}")



[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array2x6 - ksztalt: (2, 6)


In [14]:
array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Array3x4 - ksztalt: {np.shape(array3x4)}")

Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array3x4 - ksztalt: (3, 4)


In [16]:
array2x2x3 = array.reshape(2,2,3)
print("Array 2x2x3")
print(array2x2x3)
print(f"Array2x2x3 - ksztalt: {np.shape(array2x2x3)}")

Array 2x2x3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array2x2x3 - ksztalt: (2, 2, 3)


In [18]:
unsorted1D = np.array([3,6,2,4])
print(unsorted1D)
sorted1D = np.sort(unsorted1D)
print(sorted1D)

[3 6 2 4]
[2 3 4 6]


In [22]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)
sorted2D_axis0 = np.sort(unsorted2D, axis = 0)
print(f"Tablica posortowana po osi 0:\n{sorted2D_axis0}")
sorted2D_axis1 = np.sort(unsorted2D, axis = 1)
print(f"Tablica posortowana po osi 1:\n{sorted2D_axis1}")

[[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowana po osi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowana po osi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]
