<a href="https://colab.research.google.com/github/Ciastkk45/kursAI-sb10/blob/main/2_biblioteka_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version


Python 3.11.11


In [ ]:
!pip freeze | grep numpy

numpy==1.26.4


In [2]:
# ważne - importowanie numpy
import numpy as np

#tworzenie tablicy
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Array2x6 - ksztalt: {np.shape(array2x6)}")



[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array2x6 - ksztalt: (2, 6)


In [ ]:
array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Array3x4 - ksztalt: {np.shape(array3x4)}")

Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array3x4 - ksztalt: (3, 4)


In [ ]:
array2x2x3 = array.reshape(2,2,3)
print("Array 2x2x3")
print(array2x2x3)
print(f"Array2x2x3 - ksztalt: {np.shape(array2x2x3)}")

Array 2x2x3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array2x2x3 - ksztalt: (2, 2, 3)


In [ ]:
unsorted1D = np.array([3,6,2,4])
print(unsorted1D)
sorted1D = np.sort(unsorted1D)
print(sorted1D)

[3 6 2 4]
[2 3 4 6]


In [ ]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)
sorted2D_axis0 = np.sort(unsorted2D, axis = 0)
print(f"Tablica posortowana po osi 0:\n{sorted2D_axis0}")
sorted2D_axis1 = np.sort(unsorted2D, axis = 1)
print(f"Tablica posortowana po osi 1:\n{sorted2D_axis1}")

[[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowana po osi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowana po osi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [4]:
player_data = np.array([
    ("Faker", "T1", 5),
    ("TheSky", "Weibo Gaming", 1),
    ("Uzi", "Emerytowany", 0)
], dtype = [("Nick", "U30"), ("Team", "U30"), ("Worlds Title count", "i4")])

print(player_data)
#sortowanie po kolumnie o nazwie Team
print(np.sort(player_data, order ="Team"))

[('Faker', 'T1', 5) ('TheSky', 'Weibo Gaming', 1)
 ('Uzi', 'Emerytowany', 0)]
[('Uzi', 'Emerytowany', 0) ('Faker', 'T1', 5)
 ('TheSky', 'Weibo Gaming', 1)]


In [15]:
#random
from numpy import random

#<1, 11) int
for i in range(10):
  print(random.randint(1, 11))

# <0,1) float
  for i in range(10):
    print(random.rand()*10)

6
1.9616111565020844
7.195096896491705
1.5464822456578686
2.4531324483494776
4.727995120557292
2.218668432359805
8.658397569147478
3.359324548045902
3.132117413560891
2.2398420627429605
10
9.75134582165926
9.338196739581505
8.982326700334253
1.5397237434559685
3.5880983626090512
2.9237236581507844
1.3584091380236307
1.4634804631101617
6.665652541503057
5.783949341612567
1
7.400666281334009
9.182846430368677
9.357396528987298
8.400008390661597
2.4110586406364156
9.999164176092737
4.727207925081652
6.7591641384775
0.8417061577759832
4.823332161220143
9
2.6053470097335607
6.002605319249331
8.593617643080528
0.43089108254430797
9.250486726068516
2.941525775495374
7.040293688212845
7.171932668717007
2.6225387499689115
2.3886810093689603
6
3.547052239792936
7.652178454011674
9.5029742354771
2.6195180795984205
5.473585994546132
1.666279099036646
2.579034902267474
2.528471872882545
6.2838125616428675
6.521832967208189
8
3.026515015989739
7.828255197446953
3.128865640293065
6.500126825888431
8.

In [26]:
lista = [1,2,3,4]

print(random.choice(lista, 3))

[1 1 2]


In [37]:
array1D =  np.array([1,2,3,4,5,6,7,8,9])

#elementy do indeksu 4 włącznie
print(array1D[:5])

#elementy do indeksu od indeksu 2 do indeksu 4 włącznie
print(array1D[2:5])

#elementy do indeksu od indeksu 2 do końca
print(array1D[2:])

#elementy od 3 od końca do przedostatniego
print(array1D[-3:-1])

[1 2 3 4 5]
[3 4 5]
[3 4 5 6 7 8 9]
[7 8]


In [43]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

print(array2D[2,1])
print(array2D[:,2:4])
print(array2D[0:2,2:4])

for i in np.nditer(array2D):
  print(i)

12
[[ 3  4]
 [ 8  9]
 [13 14]]
[[3 4]
 [8 9]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [46]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,6]
])

result = np.where(array2D == 6)
print(result)

result = np.where(array2D % 2 == 0, True, False)
print(result)

filtered = array2D[result]
print(filtered)

(array([1, 2]), array([0, 4]))
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True  True]]
[ 2  4  6  8 10 12 14  6]
